name: social_media_widgets
description: A new flutter package for collection of common popular social media widgets like instagram story swipe and snapchat screen dismiss
version: 1.0.0+2
homepage: https://github.com/GursheeshSingh/social_media_widgets

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

